### ISSUE TITLE
Package no longer on Atom repository

### ISSUE THREAD

**Issue by kylebarron** [jfiksel/r-indent#3]
Hello,

I'm not sure if you're aware of this, but this repo is not currently published on the Atom package manager. There's no page at https://atom.io/packages/r-indent, which there would be if this were published.

Also, I'm working with a couple other people to update (slowly) the language-r package (see the forked repo [here](https://github.com/REditorSupport/atom-language-r) and some discussion [here](https://github.com/lee-dohm/language-r/issues/25)). I think the code in this repo would be great to add into the central language-r package (at least as an option in the settings). I see you haven't changed the MIT license from the upstream python-indent. Do you mind if I include your code into the repo? I'd also look at incorporating some of the upstream commits that aren't python-specific.

**Comment by jfiksel** [comment]
Hey @kylebarron, thanks for your interest in the package. As you can tell from the lack of recent commits, I've stopped maintaining this package. However, I'd be happy to have you take any code that you need. Let me know what to do so I can help.
